-- CREATE DATABASE IF NOT EXISTS `${MYSQL_DATABASE}` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
-- CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
-- GRANT ALL PRIVILEGES ON `${MYSQL_DATABASE}`.* TO '${MYSQL_USER}'@'%';
-- FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS wp_database CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'mert1234'@'%' IDENTIFIED BY 'hello1234';
GRANT ALL PRIVILEGES ON wp_database.* TO 'mert1234'@'%';
FLUSH PRIVILEGES;