CREATE DATABASE IF NOT EXISTS wp_database CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'mert1234'@'%' IDENTIFIED BY 'hello1234';
GRANT ALL PRIVILEGES ON wp_database.* TO 'mert1234'@'%';
FLUSH PRIVILEGES;